### ISSUE TITLE
Close down leaderboard at it's current form

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#103]
It appears that the leaderboard at it's current form is not providing any value but enabling unhealthy competition and cheating.
We need to ensure that this doesn't happen so we help our collegues at webcompat with less noise.

@MichaelKohler please do the following changes:

- [ ] change name "leaderboard" to List of Participants
- [ ] take out the following: 
 * This is the current ranking.Total score is 1 point for each report and 3 for each issue. 
 * Be proud of your progress
- [ ] Replace with
* We want to ensure that this is a good experience for both the attendees and the bug fixers. For that reason we decided to change the leaderboard with  a list of people participating in the initiative. However, we would like to reward people based on the quality of their work and as a result the **top 30 issues that the webcompat team consider as most imactful** will rewarded with a t-shirt.
* Be proud of your participation

**Comment by miketaylr** [comment]
Thanks @couci!
