### ISSUE TITLE
Close registrations for events

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#110]
Since we are getting close to the launch, we need to close registrations of events to ensure:
a) to minimize the bug triaging for webcompat 
b) put the attention on the social media campaign 

Steps need to be taken
* [ ] Take out registration button from host and register pages
* [ ] Replace text on the register page with: "Thank you for your interest registering an event. Unfortunately, we have stopped taking event registrations, since the campaign is over"

**Comment by couci** [comment]
fyi, I've already closed the registration form

**Comment by MichaelKohler** [comment]
done
