### ISSUE TITLE
Have an issue with buttons on the site

### ISSUE THREAD

**Issue by ghost** [mozilla/firefox57-sprint#111]
Hi! 
I have no idea what can be a problem, but red buttons on the page: https://dominospizza.ru/product/tretya_picca_v_podarok_srednyaya#!1 don't work correct. There is no issue on Chrome.

**Comment by couci** [comment]
Hey there,
that sounds like a compatibility issue, can you file a bug here: https://webcompat.com/ 

thanks :)

**Comment by ghost** [comment]
Hi,
Thank you, I will do so :)
