### ISSUE TITLE
The address bar not showing well after accessing another page

### ISSUE THREAD

**Issue by Yuessiah** [mozilla/firefox57-sprint#114]
```
Ubuntu 14.04.1
Firefox Quantum 57.0.1 (64-bit)
```
The address bar should be refreshed after user access another page.

When I modified some text in address bar, then access another page, the address bar would not be updated.

For example:
While viewing `https://github.com/mozilla/firefox57-sprint`, I clicked the `.gitignore` hyperlink, the address bar normally showed me `https://github.com/mozilla/firefox57-sprint/blob/master/.gitignore` .
but if I modify something in address bar like `https://github.com/mozilla/firefox57-sprint -> mozilla/firefox57`, after clicking the `.gitignore`, the address bar would not be updated.

**Comment by MichaelKohler** [comment]
I can reproduce this. I haven't checked out what GitHub is doing exactly and if Firefox should update the address bar or not. In any case, I think it would be helpful to file this bug at bugzilla.mozilla.org where Firefox bugs are tracked.

I'm closing this one here. Thanks for reporting.
