### ISSUE TITLE
shall we add ToC to README.md?

### ISSUE THREAD

**Issue by ghost** [mozilla/firefox57-sprint#116]
shall we add ToC to README.md? i think its relevant. looking forward. cheers

**Comment by MichaelKohler** [comment]
The README fits on the viewport of a 13' (non-retina) macbook, I don't think that is needed and might actually make it harder to find content as you would need to scroll down or read through the whole TOC.

**Comment by ghost** [comment]
ok @MichaelKohler  that sounds fair to me
