### ISSUE TITLE
Improvement: Directly load events from signups

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#13]
@couci can we make the signup registration sheet completely public? If so, I think we could directly load our data from there, thus decrease the manual workload.

**Comment by couci** [comment]
You mean without any sign-ins required right? Yes we can make that, would you like me to request the form now?

**Comment by MichaelKohler** [comment]
Basically just "Anyone on the web can view" on the responses sheet. Why would you need to request the form? Can't we just do it in the CDT folders and set the permission to that? (I will need to have edit rights on the google form part so I can play around ;))

**Comment by couci** [comment]
yes you are right :) we can totally do that

**Comment by MichaelKohler** [comment]
This is a WIP:

![Screen Shot 2017-09-14 at 23.46.35.png](https://images.zenhubusercontent.com/5965335f61b4ca3b0a740ed8/e809741f-5124-4d23-aefc-eb19ebc8e77d)

Now, let's find a library to convert country names to iso codes...
