### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#2]
This is an issue where we track how the landing page will look like.

We are forking the global sprint website and adding some extra functionalities for the need of our campaign.

**Comment by couci** [comment]
This is a mockup of the landing page.
We basically want to keep this as clean as possible.

Most of the page will be occupied by a map showing the events around the globe.
 
There are 2 action items on this page that direct to 2 subpages:
- become a host
- attend an event

On the top right corner there will be a countdown to the day of the event that will change to a count-up of links been tested on the week of the campaign

On the left there will be a menu of the websites content

![landing page](https://user-images.githubusercontent.com/7702955/29371216-0e09ee4a-82a8-11e7-9cc1-5dad849c5087.jpg)

**Comment by MichaelKohler** [comment]
As this is done so far, I'm closing this in favor of #26 for the real content.
