### ISSUE TITLE
Add content on the website

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#26]
This issue tracks the content need of the website subpages

- [ ] Landing page
- [x] Register page
- [x] Host's page
- [x] Attendees page
- [x] Resources page

**Comment by couci** [comment]
Host's page and attendees page content can be found here: https://docs.google.com/document/d/1PlCr7S9cwobRc314xLZCClibxrqdTo8p1JabycfrWH4/edit#

**Comment by MichaelKohler** [comment]
Current content has been added. Please tell me (or mark me in the doc) if there are changes to the text for the hosts or participation subpages.

Waiting for further text for the landing and registration page, happy to edit those as well. Not sure if the registration page needs more than what we have, but we definitely need some catchy phrases on why this is important on the landing page.

For the resources page, do you have anything in mind?

**Comment by couci** [comment]
On the landing page I am thinking the following:
Firefox 57 Sprint
Date (2/10 - 9/10)
Together we ensure Firefox 57 success (where it says this campaign is something)

**Comment by couci** [comment]
When we say registration page, we mean the become a host one right?
As for the Resources the idea is to have a tutorial video on how to report, I am talking with @ioana-chiorean on how to implement that

**Comment by MichaelKohler** [comment]
> When we say registration page, we mean the become a host one right?

https://mozilla.github.io/fx-webcompat-campaign/host/ is done as far as I can see. With "registration page" I meant: https://mozilla.github.io/fx-webcompat-campaign/register/ (not sure if we even need text there)

**Comment by couci** [comment]
**Edit by Michael: Content for REGISTER page:**


I would just add:
* find events close to you (above the countries list)
* register your event link

**Comment by MichaelKohler** [comment]
> I would just add:
> * find events close to you (above the countries list)
> * register your event link

This is done. Do we have any other content changes?

**Comment by couci** [comment]
For now we are good, we are missing the 2 videos we are building but they won't come before the 15th.

**Comment by couci** [comment]
Landing page in need of a small paragraph @couci (catchy thing here)

**Comment by couci** [comment]
For the landing page I was thinking something like that:
Firefox strikes back!
Firefox Quantum is soon to be launched and this is our opportunity to make Firefox rise again. Particpate in the  Firefox Quantum Sprint and make a difference

**Comment by MichaelKohler** [comment]
".. by ensuring we are fast and correct on local websites" or something like that? Currently I know why there is a sprint, but not exactly what the Sprint is about. Thoughts?

**Comment by couci** [comment]
"..by ensuring that Firefox runs smoothly in your region" thanks for the add :)

**Comment by MichaelKohler** [comment]
### Firefox strikes back!

Firefox Quantum is soon to be launched and this is our opportunity to make Firefox rise again. Participate in the Firefox Quantum Sprint and make a difference by ensuring that Firefox runs smoothly in your region.

Final approval? @couci

**Comment by couci** [comment]
yes go for it
