### ISSUE TITLE
Reporting form and leadershipboard should stand alone in the menu

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#27]
Considering the importance of the reporting form (and the need of being easy to find) and the gamification for leadershipboard those two pages should be easy to find.

Thus I think they should be displayed on the side menu as side pages so they are easy to catch the eye

**Comment by MichaelKohler** [comment]
Sounds good, I'll leave the "Resources" item empty for now, as far as I know we'll use that one for some other stuff once content is ready.
