### ISSUE TITLE
Become a host

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#3]
**Become a host subpage**

The main menu on the left will remain

The page will have the following components:

- Register your event: this will link to a form where people can register
- How to host an event: this will have text info on useful tips
- Workflow of the event
- Resourced you can request

![become a host](https://user-images.githubusercontent.com/7702955/29373637-322adcb0-82af-11e7-83f2-5aa7eada9a7f.jpg)

**Comment by MichaelKohler** [comment]
As this is done so far, I'm closing this in favor of #26 for the real content.
