### ISSUE TITLE
Do a content review and check for typos/missing links

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#30]
Once we are on a good level content-wise we need to check the website to find any missing link references and typos in the text. I guess we can outsource this further once we did an initial round to fix the links :)

**Comment by MichaelKohler** [comment]
Currently missing links:

- [ ] Event Registration (for hosts to register a new event)
- [ ] Swag/Budget Request Form

**Comment by couci** [comment]
On event registration I thought we would encourage people to register on the pages each one has built, no?

**Comment by MichaelKohler** [comment]
> On event registration I thought we would encourage people to register on the pages each one has built, no?

This is the link to the form for hosts. So we can keep track and list who and where events happen. (changed the phrasing above in the comment).

**Comment by couci** [comment]
So we are in need of a design similar to what we have on the report form right?

**Comment by MichaelKohler** [comment]
> So we are in need of a design similar to what we have on the report form right?

This is either a Google Form with the registration content we discussed *or* a similar form on the website itself that reports to a Google Form. In both cases we need a Google form. If we want to have the form on the website itself (and therefore decrease the amount of manual work), check #13. In any case, this here is *just* about adding the final link to "Register your own event" on https://mozilla.github.io/fx-webcompat-campaign/host/. Also we probably want that link on the "REGISTER" page as well.

**Comment by MichaelKohler** [comment]
Event registration was added, budget/swag link is now tracked in #45
