### ISSUE TITLE
Decide on final date and name

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#32]
As decisions on the final date and name require a quick content update, I'm filing this issue.

- [ ] Implement the final campaign name (including logo and all occurances of the name, including repo)
- [ ] Implement final date (mostly for the title on the landing page and the countdown)

**Comment by couci** [comment]
On date I am thinking first week of October, that is: Monday the 2nd as the first day of events.

On naming I am thinking on landing on "Firefox 57 Sprint"

**Comment by MichaelKohler** [comment]
Assigning to me to reflect that on website.
