### ISSUE TITLE
Decide on domain

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#33]
Currently we're running at mozilla.github.io/<repositoryname>. We need to talk to ParSys if we need <campaignname>.mozilla.community for example. @couci what do you think?

I might need to change the base url of the website in the code depending on the domain.

**Comment by couci** [comment]
I would like the mozilla.community. I am leaning on "firefox57-sprint.mozilla.community" what do you think?

**Comment by MichaelKohler** [comment]
We are currently going for firefoxsprint.mozilla.community

**Comment by ranjithrajv** [comment]
@MichaelKohler firefoxsprint.mozilla.community looks good.
