### ISSUE TITLE
Improve Design

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#36]
I currently see the following problems/concerns with our design:

- [x] Links are quite hard to read, they should be darker
- [x] Logo is hard to read, we might want to choose a darker blue (fixing the first point as well)
- [x] Landing page image is currently a placeholder, do we have something better?
- [ ] Having the countdown/sites tested counter in the header does not really resonate with me, do we find another place for it?
- [x] We are currently using Mozilla branding for the title in the landing page header, but nowhere else, I think we should get rid of that as this is Firefox and only use it for the logo

Do we need help from OpenDesign here? I'd rather not do a complete rewrite of everything, but these things could definitely be adjusted quite easily. @couci any thoughts?

Before any implementation, we need to specify what we want to change.

**Comment by couci** [comment]
On landing page image I was thinking on this: http://images.derstandard.at/t/12/2017/08/06/firefox.jpg
On links, let's put a darker blue and make the links buttons on the landing page a different colout

I am not sure why we should get rib of mozilla branding right now. On opendesign yes sure, how much time do you believe you need for implementation from the time you get feedback?

**Comment by MichaelKohler** [comment]
I've applied some changes before we announced this to the Reps. I think we're ok for now.
