### ISSUE TITLE
Creation of the event registration form

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#38]
This issue is to track the creation of the event registration form:
Content to be added:
- [x] Event place (city, country)
- [x] Event date
- [x] Name of the host
- [x] mozillian profile
- [x] link where people can register at your event (it can be from an event page to the reps portal to a meet-up page)
- need of swag and budget (answer yes/no)

**Comment by MichaelKohler** [comment]
Do we want to show the name of the organizer in the list on https://mozilla.github.io/fx-webcompat-campaign/register/ ? If so, we also need to have the clean name available, not just the mozillians link.

**Comment by couci** [comment]
yes, isn't the name of the host what you're referring?

**Comment by MichaelKohler** [comment]
Nevermind me..

**Comment by couci** [comment]
The swag and budget form will need to go later since we first need confirmation that they have at least 10 people registered

**Comment by couci** [comment]
url for form here: https://goo.gl/forms/0cVVoz8rjG0noHsI2

@MichaelKohler please review

**Comment by MichaelKohler** [comment]
Thanks, looks good. Let's continue with #39
