### ISSUE TITLE
Attend an event page

### ISSUE THREAD

**Issue by couci** [mozilla/firefox57-sprint#4]
Attend an event subpage

The menu on the left stays the same

Subcomponents:
- Find a local event in your area (directing to the events subpage)
- Steps on how to register: sign up link
- How to take action from your home (instructions on how one can take action solo)

![attend an event](https://user-images.githubusercontent.com/7702955/29373997-345680ec-82b0-11e7-968a-89bdd399f37e.jpg)

**Comment by MichaelKohler** [comment]
Not sure anymore what we discussed. About the "Steps on how to register", we will eventually display the sign up link per event on the events overview. What exactly did we mean here?

**Comment by couci** [comment]
Basically a text on how one can search for a place near to him and what to do in order to sign up (click on the link provided by every organizer).
I think you're right sign up link doesn't make sense here

**Comment by MichaelKohler** [comment]
As this is done so far, I'm closing this in favor of #26 for the real content.
