### ISSUE TITLE
"missing link" on Resources you can request paragraph

### ISSUE THREAD

**Issue by irvin** [mozilla/firefox57-sprint#45]
https://firefoxsprint.mozilla.community/host/
> Do you need funding and swag? You can request your event package here - **_missing link_**!!

**Comment by MichaelKohler** [comment]
Assigning to @couci for the form.

**Comment by GuteMonik** [comment]
Hello!
This the link of the Colombian event: https://github.com/GuteMonik/Firefox57 
And this in Reps portal: https://reps.mozilla.org/e/mozilla-firefox-57-sprint/
They could help me manage the swag please. Thanks! M.

**Comment by couci** [comment]
Funding form here: https://goo.gl/forms/fkwubidAAnvK40vF3

**Comment by couci** [comment]
Swag request here: https://goo.gl/forms/4FEhEEPkujEt3TYd2

**Comment by couci** [comment]
@MichaelKohler small changes on the page:

- People can request budget only *after* the event with an indication of the receipt
- Take out the t-shirts from the list of the swag, those will be given to the first 50 of the leaderboard
