### ISSUE TITLE
Figure out what to do with Website list

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#48]
Feedback by @kelimuttu in https://github.com/mozilla/firefox57-sprint/issues/34#issuecomment-325583354:

> And apparently, Alexa only provide a limited number of 50 websites for the free account. In order to see the full list, we need to subscribe. So, I think we better come up with another options for the website reference. I can't think of anything right now tho'.
> And we can probably put something in the website to encourage the host to ask the participants test their own favorite websites. Just so people is not only focus on the Alexa list.

@couci what do you think?

**Comment by couci** [comment]
I like the idea of checking their own websites as well. As for the Alexa list, does it make sense for me to buy a subscription and copy past somewhere were Mozillians can check it out?

**Comment by MichaelKohler** [comment]
As far as I can see it's $25 per 100 URLs. That's gonna be really expensive if we want to cover most countries.

**Comment by MichaelKohler** [comment]
.. and I'm not sure if that is even allowed to be republished. We'll figure it out.

**Comment by couci** [comment]
Priyanka will provide the India site
@couci to check with George about buying the data

**Comment by SandeepKapalawai** [comment]
Hi Micheal,

I have checked Alexa Indian List of websites and found that only few of websites are listed in trail version.

I would like to suggest you the below websites with more traffic : 

*Linkedin.com (https://www.linkedin.com)
*Alibaba (http://india.alibaba.com/index.html)
*Daink Bhasker(https://www.bhaskar.com/site-take-over-ads)
*Make my trip(https://www.makemytrip.com/)
*99 acres (https://www.99acres.com/NRI-Real-Estate.htm)
*Bharath Matrimony(https://www.bharatmatrimony.com/)
*viu(https://www.viu.com/in-hindi/en)


Best,
Sandeep

**Comment by MichaelKohler** [comment]
Hi Sandeep

Some Reps have started to do their own list for India: https://public.etherpad-mozilla.org/p/firefoxquantumsprint-india

**Comment by SandeepKapalawai** [comment]
Thank you Michael i will do check it out

**Comment by MichaelKohler** [comment]
@couci ready to change the link/text whenever you are

**Comment by lkappeler** [comment]
In this [Post](https://www.quora.com/What-are-the-top-100-000-most-visited-websites) I have found am S3 link to the [top 1Mio list form Alexa](http://s3.amazonaws.com/alexa-static/top-1m.csv.zip). The Comment says its auto generated every day. The one I downloaded is from yesterday. The entries are matching with the ones from [alexa's top 500](https://www.alexa.com/topsites)

**Comment by kelimuttu** [comment]
We need the region-specific data so we decided to purchase the list anyway. But yeah, we can definitely use the 1 million list as a global reference as well. Thanks for pointing out @lkappeler

**Comment by couci** [comment]
Here is the list of the 200 first websites for the countries participating shorted alphabetically:  https://docs.google.com/spreadsheets/d/1KCT5Ytuu8tyC559TXVo-lIlv4mZVPGhn8qQe-qSTgm8/edit#gid=1569236874

@MichaelKohler here is the text: Check this list of the [200 most famous website](https://docs.google.com/spreadsheets/d/1KCT5Ytuu8tyC559TXVo-lIlv4mZVPGhn8qQe-qSTgm8/edit#gid=1569236874) in your local and choose the website you want to test. If you can't find your country you can also check the Alex list. Please don't start at the top to make sure we do not only test the first 10.

**Comment by MichaelKohler** [comment]
Will add that tonight.

**Comment by SandeepKapalawai** [comment]
Hi @MichaelKohler ,

I have a concern with the leader board points in below case: Please check :

1. For the first time when we tested a site ex: www.google.co.in and we didn't find any issues submit as" we didn't find any issue with the site by selecting .No" .This will be added as 1 point.
2. But in case if we find the issue when we tested for 2nd time for the same website (www.google.co.in) and reported, it was submitted and could see that there no increment in the points.

Can you please provide your thoughts for the same.

Best,
Sandeep

**Comment by MichaelKohler** [comment]
@sonusandeep we filter "double" entries to avoid testing the same site over and over again to get points. This is done by nickname+sitetested. 

@couci thoughts?

**Comment by lkappeler** [comment]
This is caused by https://github.com/mozilla/firefox57-sprint/issues/88. Since we count domains unique the issues form the first entry are counted. I think we should add an additional check if there are more issues than in the fist check and count the check with more issues

**Comment by SandeepKapalawai** [comment]
Thank you @MichaelKohler  for clarifying.

@lkappeler  +1

**Comment by MichaelKohler** [comment]
@sonusandeep this will be handled in https://github.com/mozilla/firefox57-sprint/issues/88

**Comment by SandeepKapalawai** [comment]
Sure Thank you @MichaelKohler
