### ISSUE TITLE
Add GA

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#49]
@hmitsch, can we add ourselves to your GA metrics? (And also have them posted to the oi-analytics channel?)

Just need the snippet for it.

**Comment by hmitsch** [comment]
Yes, yes, yes ... I suggest using GTM. Nikos can help. Can you tag him? I
am on #familyTime.

**Comment by hmitsch** [comment]
## Google Tag Manager Configuration

 **Paste this code as high in the <head> of the page as possible:**
`<!-- Google Tag Manager -->`
`<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-M9TL4WH');</script>`
`<!-- End Google Tag Manager -->`

**Additionally, paste this code immediately after the opening <body> tag:**
`<!-- Google Tag Manager (noscript) -->`
`<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M9TL4WH" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`
`<!-- End Google Tag Manager (noscript) -->`

**Comment by hmitsch** [comment]
I set the Google Analytics ID via GTM, it is UA-84301250-9.
I also configured GTM to track outbound links.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/869692/30083685-c686b786-928f-11e7-9671-0c081fa15612.png">

**Comment by hmitsch** [comment]
@MichaelKohler please let me know when it is implemented, in order to test it. Thank you!

**Comment by hmitsch** [comment]
@comzeradd if you have any implementation hints, feel free to comment on this issue.

**Comment by comzeradd** [comment]
@MichaelKohler Just make sure to wrap the GTM inside a DoNotTrack check. The easiest way to do it is to use the [dnt-helper](https://github.com/schalkneethling/dnt-helper) library and then do something like this: https://github.com/mozilla-iam/sso-dashboard/blob/master/dashboard/static/js/ga.js

**Comment by MichaelKohler** [comment]
Thanks, we will do that :)

**Comment by MichaelKohler** [comment]
@hmitsch I've added it to https://firefoxsprint.mozilla.community/register/ however, it says 404 on the https://www.googletagmanager.com/gtm.js?id=GTM-M9TL4WH . Do you need to activate the URL in Tag Manager so the file gets served? Or are they only counting URL access and always return 404?

![screen shot 2017-09-15 at 02 01 21](https://user-images.githubusercontent.com/330324/30460833-ce51991e-99b9-11e7-8444-51fd3e7987ae.png)

**Comment by hmitsch** [comment]
Baah ... PEBCAK ... Container not published ...

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/869692/30507063-4b274494-9a81-11e7-8f2c-b5508d9130d5.png">

**Comment by hmitsch** [comment]
Works now, 404 is now a 200. :-)

https://www.googletagmanager.com/gtm.js?id=GTM-M9TL4WH

**Comment by MichaelKohler** [comment]
Thanks!

**Comment by hmitsch** [comment]
Attn @MichaelKohler 

**GA works like a charm:**
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/869692/30515560-92c08f1e-9b2a-11e7-8647-8f637a500d00.png">

Here is an example of the benefit of **integrating GA via GTM**. We have link click events and can track **clicks to properties outside** the current site (e.g. lines 3, 7, 9, 10):
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/869692/30515586-faff5cf4-9b2a-11e7-9ea2-6dffa87e4c1c.png">

PS: I have requested to extend my Arc.ai account credit to add **regular analytics posts on #oi-analytics**. Would you want **weekly or daily** stats?

**Comment by MichaelKohler** [comment]
Nice! Regarding oi-analytics, I think weekly is fine.

**Comment by hmitsch** [comment]
Cool, the guy behind Arc.ai usually gets back quickly. Maybe we can still get it set up in time for Monday. Fingers crossed.

**Comment by hmitsch** [comment]
FYI, I also configured two goals in GA.

One tracks against the G Suite document URL, the other tracks URL fragments (URIs). 
If possible, ping me if these parameters change. 

<img width="769" alt="image" src="https://user-images.githubusercontent.com/869692/30515769-6013e58a-9b2e-11e7-9504-b2de3d8663a8.png">

**Comment by hmitsch** [comment]
**arc.ai summary** created and configured for weekly alerts at 9am (CET) on Mondays.

You will see something like this on #oi-analytics in 11 hours:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/869692/30524529-c463fcba-9bf5-11e7-9ff2-d98828f9dec4.png">

-Henrik

**Comment by hmitsch** [comment]
Interesting conversion funnel for the "attend an event" goal ... looks like the site works quite well. Sample rate is still very, very small though.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/869692/30524545-37a45d82-9bf6-11e7-8d01-1cce24d4e79e.png">
