### ISSUE TITLE
Feature: Order Event locations alphabetically

### ISSUE THREAD

**Issue by lkappeler** [mozilla/firefox57-sprint#57]
Event locations shall be sorted alphabetically.
This would make the event easier to find if there are multiple events in a certain country eg. India 

![screenshot from 2017-09-15 14-46-13](https://user-images.githubusercontent.com/3371760/30483235-6fc6fdd6-9a26-11e7-827a-f4928940ed8d.png)

cc: @MichaelKohler

**Comment by MichaelKohler** [comment]
Makes sense!
