### ISSUE TITLE
Map doesn't load for /register

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#61]
The Map doesn't load for https://firefoxsprint.mozilla.community/register/ as there is a country (West Bank) that we do not have in our mapping list for the map icons. 

Proposed solution:
* Handle that error correctly
* Show placeholder map for West Bank

@couci as we don't have a map icon for West Bank, I would show a placeholder (though that can get quite political). I'd propose the following: http://mapglyphs.com/middle-east-map

With the new design this won't be an issue anymore as we won't have those anymore.

**Comment by couci** [comment]
I agree let's move forward with the suggestion added since this is temporary
