### ISSUE TITLE
Implement Leaderboard Design

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#68]
- [x] Implement header
- [x] Implement leaderboard
- [x] Implement new scoring calculation
- [ ] Implement background image

(Not finalized yet)
![firefoxsprint_page05_leaderboard](https://user-images.githubusercontent.com/330324/30562657-926b51ca-9cbf-11e7-95b9-828d405995b8.png)

**Comment by MichaelKohler** [comment]
This is done in "newdesign" branch apart from the background images. Will add this to the followup issue.

**Comment by ranjithrajv** [comment]
Started testing sites for Firefox Quantum Sprint and ended up finding a bug in leader board calculation algorithm :P
it's not detecting duplicate reports, please check.

**Comment by ranjithrajv** [comment]
Please add an option to check submitted reports, when clicked on the number of sites tested. That would be of great help.
