### ISSUE TITLE
Add offset for overlapping locations

### ISSUE THREAD

**Issue by lkappeler** [mozilla/firefox57-sprint#78]
There are a few events on the same location eg. Paris. Since we lookup the locations with googles geodata service the markers are exactly on the same position which is resulting in only one clickable marker. (I guess either the the first or last one rendered)

**Comment by maqboolkhan** [comment]
Possible solution can be adding random offset with `lang` and `lat `
source [Stackoverflow](https://stackoverflow.com/questions/3548920/google-maps-api-v3-multiple-markers-on-exact-same-spot)

**Comment by lkappeler** [comment]
Thanks for your suggestion!

**Comment by lkappeler** [comment]
Added offset https://github.com/lkappeler/geodata-fetcher/commits/master

@MichaelKohler Please decrease cronjob interval to max 4/day since the rate limit is about 2500 requests per day
