### ISSUE TITLE
Duplicate entries are counted in Leaderboard

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/firefox57-sprint#88]
The leaderboard counts duplicate entries. We should at least filter for unique domains tested.

**Comment by MichaelKohler** [comment]
see https://github.com/mozilla/firefox57-sprint/issues/48#issuecomment-333833213

**Comment by lkappeler** [comment]
@couci Would you rather only count the issues found on a retest or the retest as a unique test and the found issues?

cc @MichaelKohler

**Comment by couci** [comment]
I think it's better in the counting to count only the retest since the website has already been counted before

**Comment by JeanPaulLucien** [comment]
What about count of each of the tested website and just decrease price (points) for this?

**Comment by MichaelKohler** [comment]
I'm closing this PR as this project is done and I'm putting this repository into read-only mode.
