### ISSUE TITLE
Add marker clustoring

### ISSUE THREAD

**Issue by lkappeler** [mozilla/firefox57-sprint#90]
Add some [clustoring](https://developers.google.com/maps/documentation/javascript/marker-clustering) to the map after finishing #78.

@MichaelKohler Do you think this is ok with the design?

**Comment by ranjithrajv** [comment]
@lkappeler this is a good idea, nice!

**Comment by MichaelKohler** [comment]
Sounds good to me!

**Comment by maqboolkhan** [comment]
Awesome @lkappeler  👍
