### ISSUE TITLE
Fake bold in hero text

### ISSUE THREAD

**Issue by fitojb** [mozilla/firefox57-sprint#91]
Fira Sans (and I’m so glad you used Fira instead of Open) looks hideous due to a missing weight call.
![captura de pantalla de 2017-09-30 19-59-35](https://user-images.githubusercontent.com/554953/31050740-eeb71b40-a619-11e7-8217-2ed32ff117ab.png)

**Comment by MichaelKohler** [comment]
What exactly would you suggest? The current one is the same as font-weight: 700 would be.
