### ISSUE TITLE
Firefox Quantum Sprint website - Prishtina, Kosovo fix

### ISSUE THREAD

**Issue by altinukshini** [mozilla/firefox57-sprint#95]
The issue is on: https://firefoxsprint.mozilla.community/register

Pin in Prishtina, Kosovo sends to 'wrld' (https://firefoxsprint..../#wrld) not 'xk' and Kosovo is also missing the Map icon.

Maybe whoever's entering the data on the website is not aware of Kosovo's ISO code 'xk', but yet MapGlyph is there http://mapglyphs.com/kosovo 

Thnx to @Mte90 for referring me to this repo!

**Comment by MichaelKohler** [comment]
This is a script doing this. Probably Kosovo just doesn't map to anything for now and therefore falling back to "wrld". Will check it out in the next few hours.

**Comment by MichaelKohler** [comment]
This should be fixed in 10 minutes (Cache applies to the website).
