### ISSUE TITLE
[urgent] NSFW sites in Quantam sprint list

### ISSUE THREAD

**Issue by tsl143** [mozilla/firefox57-sprint#99]
The list of websites given for testing on the day has few NSFW websites, these will be accessed in school/colleges.

https://docs.google.com/spreadsheets/d/1KCT5Ytuu8tyC559TXVo-lIlv4mZVPGhn8qQe-qSTgm8/edit#gid=1569236874

**Comment by shashwatjain2020** [comment]
Would be working on it! @tsl143  Please assign it to me!

**Comment by tsl143** [comment]
@niecstudent , it has been done, thanks for your interest :)
